version: "3"
services:
  postgres:
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
    ports:
      - "3001:3001"
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    ports:
      - "3000:3000"
